### ISSUE TITLE
fix package deps

### ISSUE THREAD

**Issue by transitive-bullshit** [aalbacetef/google-dns-api#5]
![CleanShot 2024-10-12 at 14 46 21@2x](https://github.com/user-attachments/assets/f960d01c-df7a-4954-811e-d3d392588ebf)

Many of these should probably be dev deps (typescript, tsx, types, etc).

**Comment by aalbacetef** [comment]
Agreed, I'll put together a PR for that. 

Thanks for bringing that to my attention!
